/** Descriptions shared by equivalent parameters; explicit tool descriptions always win. */
export const PARAMETER_DESCRIPTIONS: Record<string, string> = {
  "filters": "Filters combined according to this tool's query schema. Use provider field names and the declared operators.",
  "searchType": "Search surface to report, such as web, image, video, news or Discover. Availability depends on the property.",
  "searchTypes": "Search surfaces to compare. Each surface is queried separately; do not sum overlapping surfaces.",
  "datePreset": "Named reporting period. Use the custom date range when you need exact start and end dates.",
  "dateRange": "Explicit reporting start and end dates in YYYY-MM-DD format.",
  "timeRange": "Explicit provider reporting period with since and until dates.",
  "startDate": "First date of the reporting period, in YYYY-MM-DD format.",
  "endDate": "Last date of the reporting period, in YYYY-MM-DD format, on or after startDate.",
  "since": "Beginning of the requested reporting period; use the format accepted by the provider.",
  "until": "End of the requested reporting period; use the format accepted by the provider.",
  "orderBy": "Field used to order report rows.",
  "orderField": "Provider field used to order report rows.",
  "orderDirection": "Sort direction for the selected ordering field.",
  "orderType": "Sort direction for the selected ordering field.",
  "sortBy": "Metric or dimension used to rank the returned results.",
  "sort": "Native provider ordering expressions.",
  "limit": "Maximum number of returned items or rows. The declared bounds and default apply; use pagination for additional results.",
  "topN": "Maximum number of highest-ranked results to return.",
  "pageSize": "Maximum items requested per page. Follow the returned pagination information for remaining results.",
  "page": "Page number to request, starting at 1.",
  "offset": "Zero-based number of rows to skip before returning results.",
  "bookmark": "Opaque Pinterest pagination bookmark returned by the previous response. Omit on the first request.",
  "after": "Opaque cursor for the next page returned by Meta.",
  "before": "Opaque cursor for the previous page returned by Meta.",
  "includeUnchanged": "Include entries with no observed change in the comparison.",
  "minImpressions": "Minimum reported impressions required for a row to enter the analysis.",
  "objectives": "Analysis goals that determine the recommended large-site sampling strategy.",
  "pageLimit": "Maximum number of pages considered for the sampling plan.",
  "maxInspectionUrls": "Maximum URL Inspection candidates included in the plan; inspection calls consume provider quota.",
  "minImpressionsForLowCtr": "Minimum impressions before a page is considered for low-CTR analysis.",
  "staleSitemapDays": "Number of days after which a sitemap's last download is considered stale.",
  "continueOnError": "Continue with other URLs when one inspection fails, returning individual failures.",
  "dimension": "Reporting dimension used to group and compare results.",
  "maxClusters": "Maximum query clusters to return.",
  "topQueriesPerCluster": "Maximum example queries returned for each cluster.",
  "minPages": "Minimum distinct pages ranking for a query before it is considered a cannibalization candidate.",
  "adAccountId": "Owning advertising account ID. Use the exact ID returned by account discovery; do not substitute a campaign or business ID.",
  "advertiserId": "TikTok advertiser account ID as a string.",
  "customerId": "Google Ads customer ID, without hyphens.",
  "propertyId": "Google Analytics property ID; use the property, not the account or measurement ID.",
  "level": "Entity or aggregation level for the requested report.",
  "dataLevel": "TikTok reporting aggregation level. Metrics and dimensions must be compatible with this level.",
  "granularity": "Time bucket used to aggregate reporting rows.",
  "columns": "Native Pinterest reporting column names. Discover supported columns before selecting metrics.",
  "executionMode": "Choose the supported synchronous, asynchronous or automatic report execution strategy.",
  "entityIds": "Exact IDs of the entities to include in the selected reporting level.",
  "targetingTypes": "Native targeting categories used to break down delivery.",
  "clickWindowDays": "Click-through attribution window, in days.",
  "engagementWindowDays": "Engagement-through attribution window, in days.",
  "viewWindowDays": "View-through attribution window, in days.",
  "conversionReportTime": "Whether conversions are assigned to the ad action date or the conversion date.",
  "attributionTypes": "Provider attribution categories included in the report.",
  "reportingTimezone": "Provider reporting timezone selector. Keep it consistent when comparing periods.",
  "campaignIds": "Restrict results to these campaign IDs.",
  "adGroupIds": "Restrict results to these ad group IDs.",
  "adgroupIds": "Restrict TikTok results to these ad group IDs.",
  "adIds": "Restrict results to these ad IDs.",
  "campaignId": "Exact campaign ID in the selected advertising account.",
  "adGroupId": "Exact ad group ID in the selected advertising account.",
  "adSetId": "Exact Meta ad set ID in the selected advertising account.",
  "adId": "Exact ad ID in the selected advertising account.",
  "entityId": "Exact ID of the entity selected by this operation. It must belong to the selected account.",
  "onlyWithPeriodDelivery": "Keep only creatives with observed delivery in the requested date range.",
  "breakdown": "Native reporting breakdown used to group results.",
  "breakdowns": "Native reporting breakdowns. Check compatibility before combining them.",
  "productGroupIds": "Restrict reporting to these product group IDs.",
  "productItemIds": "Restrict reporting to these product item IDs.",
  "includeProductSamples": "Include a limited sample of product records alongside inventory diagnostics.",
  "sampleProductGroups": "Maximum product groups to sample for inventory diagnostics.",
  "reportName": "Provider report name identifying the requested report recipe.",
  "conversionProductAttributionType": "Pinterest product-conversion attribution category.",
  "conversionProductBreakdown": "Pinterest product-conversion grouping level.",
  "productSkuIds": "Restrict product-conversion reporting to these SKU IDs.",
  "request": "Exact request schema name to inspect before composing a write payload.",
  "entity": "Entity collection or level to inspect.",
  "entityType": "Provider entity type to retrieve.",
  "entityStatuses": "Native status values used to filter the entity collection.",
  "statusFilter": "Native status values used to filter the returned entities.",
  "targetingType": "Targeting dictionary to inspect, such as interests, locations or demographics.",
  "interestId": "Native interest ID for the targeting lookup.",
  "mode": "Operation or analysis mode. Only the values declared in this schema are supported.",
  "matchTypes": "Keyword match types included in the lookup.",
  "countryCode": "Country code used to localize keyword or targeting results.",
  "keywords": "Keyword phrases to analyze; use the language and market of the intended audience.",
  "term": "Search term used for the keyword lookup.",
  "terms": "Search terms used for the keyword lookup.",
  "audienceId": "Exact ID of the audience to inspect or modify.",
  "customerListId": "Exact customer-list ID. Reading metadata does not upload customer data.",
  "businessId": "Exact business account ID used for the lookup.",
  "accountType": "Provider account category used to filter results.",
  "ownershipType": "Filter audiences by provider ownership category.",
  "excludeNca": "Whether to exclude Pinterest new-customer-acquisition audiences from this lookup.",
  "audienceInsightType": "Pinterest audience-insights category to request.",
  "surfaces": "Conversion-setup surfaces to inspect, according to the supported values.",
  "includeDeletedTags": "Include deleted conversion tags in diagnostics.",
  "lookbackPeriod": "Provider lookback period used for conversion diagnostics.",
  "sourcePlatform": "Filter conversion data by source platform.",
  "ingestionSource": "Filter conversion events by ingestion source.",
  "catalogId": "Exact product catalog ID accessible to the selected account.",
  "feedId": "Exact catalog feed ID.",
  "processingResultId": "Exact catalog feed processing result ID to inspect.",
  "productGroupId": "Exact product group ID.",
  "productSetId": "Exact Meta product set ID belonging to the selected catalog.",
  "exportType": "Provider export category to request.",
  "action": "Supported operation within this tool's scoped provider surface.",
  "includeDetails": "Include detailed provider records in addition to summary information.",
  "leadFormId": "Exact lead form ID to inspect.",
  "subscriptionId": "Exact subscription ID to inspect.",
  "assetId": "Exact provider asset ID.",
  "memberId": "Exact business member ID used for the read lookup.",
  "partnerId": "Exact business partner ID used for the read lookup.",
  "pinId": "Exact Pinterest pin ID.",
  "pinIds": "Exact Pinterest pin IDs to include.",
  "metrics": "Native or documented calculated metric names to request. Check compatibility with the selected dimensions.",
  "metric": "Metric used for the analysis; use a name from the platform metric catalogue.",
  "boardId": "Exact Pinterest board ID.",
  "searchTerm": "Text used to filter or search the selected collection.",
  "region": "Provider region selector used to localize trends.",
  "productRegion": "Region used for product trend analysis.",
  "trendType": "Provider trend category to return.",
  "interests": "Native interest categories used to filter trends.",
  "genders": "Native gender categories used to filter aggregate trends.",
  "ageBuckets": "Native age groups used to filter aggregate trends.",
  "includeKeywords": "Include related keyword details in the trend response.",
  "includeDemographics": "Include available aggregate demographic breakdowns.",
  "productCategories": "Native product category IDs or values used to filter trends.",
  "verticals": "Native business verticals used to filter trends.",
  "productLookbackDays": "Product-trend lookback window, in days.",
  "productEngagementType": "Engagement signal used for product-trend analysis.",
  "featuredInterest": "Featured interest category for the trends lookup.",
  "reportType": "Native provider report type; determines supported metrics and dimensions.",
  "promotionId": "Exact Pinterest product-group promotion ID.",
  "type": "Provider object or operation type selected from this schema's allowed values.",
  "productBreakdown": "Native product grouping used to join catalog items with reported insights.",
  "catalogProductLimit": "Maximum catalog product records read for the join.",
  "includeAdsets": "Include ad set configuration when checking brand safety.",
  "includeBlockLists": "Include accessible brand-safety block-list metadata.",
  "includeRawTargeting": "Include the native targeting specification for diagnostics.",
  "cellEntityType": "Entity type represented by experiment cells.",
  "includePagePosts": "Read related Facebook Page posts when the token has permission.",
  "includeInstagramMedia": "Read related Instagram media when the token has permission.",
  "includeInsights": "Include available insight metrics; additional provider permissions may be required.",
  "edge": "Allowlisted Meta Graph edge to read on the selected node.",
  "fields": "Native provider fields to return. Select only fields supported by the chosen object or report.",
  "filtering": "Native provider filter expressions; credentials and account overrides are not allowed.",
  "includeSummary": "Request the provider's available summary or total-count metadata.",
  "actionBreakdowns": "Meta action-level breakdowns, subject to Insights compatibility rules.",
  "actionAttributionWindows": "Meta attribution windows used to attribute action metrics.",
  "timeIncrement": "Provider time-bucket size or supported aggregate value.",
  "locationTypes": "Location dictionary categories to include in targeting search.",
  "adFormat": "Native Meta ad preview format; must be compatible with this ad's creative.",
  "handle": "Asynchronous catalog batch handle returned by the submission to inspect.",
  "keepEmptyRows": "Keep provider rows whose selected metrics are all zero, where supported.",
  "sampleLimit": "Maximum records included in the diagnostic sample.",
  "isOpenFunnel": "Allow users to enter at any funnel step instead of requiring the first step.",
  "visualizationType": "Supported funnel visualization mode.",
  "breakdownLimit": "Maximum breakdown values to include in the funnel response.",
  "nextActionLimit": "Maximum next actions returned for each funnel step.",
  "fallbackToStepCounts": "If the advanced funnel is unavailable, return independent step counts with the limitation made explicit.",
  "report": "Native GA4 report request object for this endpoint.",
  "reports": "Native GA4 report request objects to execute in one batch.",
  "dimensions": "Native reporting dimensions. Validate compatibility with the selected metrics.",
  "compatibilityFilter": "Limit compatibility results to the requested GA4 compatibility category.",
  "collection": "Allowlisted administrative resource collection to read.",
  "settings": "Property configuration surfaces to inspect.",
  "includeRecurring": "Include recurring audience-export configurations.",
  "audienceExportName": "Full GA4 audience-export resource name returned by list_audience_exports.",
  "queryLifetime": "Request lifetime reporting instead of the explicit reporting period where TikTok supports it.",
  "declineThresholdPct": "Percentage decline used as a candidate signal for creative fatigue, requiring further evidence.",
  "includeSavedAudiences": "Include accessible saved-audience metadata in the overlap analysis.",
  "overlapThreshold": "Overlap threshold used to flag audience pairs, in the units declared by this schema.",
  "serviceType": "TikTok report service category.",
  "catalog": "Allowlisted targeting dictionary or catalog to inspect.",
  "query": "Search text used to find matching entries in the selected catalogue.",
  "parameters": "Native query parameters for this allowlisted read endpoint. Do not provide credentials or account overrides.",
  "account_id": "Exact account ID selected for this platform in the GetMCPAds workspace.",
  "platform": "Platform key identifying the connected advertising or analytics source.",
  "id": "Exact saved object ID returned by the corresponding create or list tool.",
  "revision": "Last known object revision, used to reject conflicting updates. Read the object before editing.",
  "name": "Human-readable name for this object.",
  "title": "Human-readable title for the resulting object or review.",
  "clientLabel": "Display label identifying the client in the saved view.",
  "config": "Complete saved-view configuration, including source, selected account, period and display options.",
  "subject": "Entity or creative subject whose dated performance will be analyzed.",
  "compare_previous": "Include the immediately preceding period of equal duration for comparison.",
  "profile": "Creative brief profile containing the client's business context and analysis preferences.",
  "primaryMetric": "Metric used to rank or evaluate the review; it must be available for the selected platform.",
  "direction": "Whether higher or lower values of the primary metric represent improvement.",
  "creative_ids": "Exact creative IDs to include in this review.",
  "request_id": "Caller-generated request identifier. Reuse it for a retry of the same operation to avoid duplicate work.",
  "expiresInDays": "Number of days before the public review sharing link expires.",
  "client_id": "Exact saved business-client workspace ID.",
  "review_id": "Exact review ID returned by the review creation or listing tool.",
  "page_id": "Exact page identifier within the landing-page review.",
  "entity_id": "Exact entity identifier in the selected review or platform context.",
  "source_key": "Source identifier returned by the business review; keep the platform/account association intact.",
  "metric_key": "Exact metric key in the review evidence.",
  "follow_up_on": "Follow-up date for the decision, using the format declared in this schema.",
  "hypothesis": "Specific hypothesis to record, supported by the review evidence.",
  "successCriterion": "Measurable condition used to decide whether the recorded action succeeded.",
  "outcome": "Observed outcome to record; distinguish evidence from an untested expectation.",
  "status": "Status selected from the allowed values for this object or operation.",
  "retry_source": "Source identifier to retry after reviewing its reported error.",
  "site_origin": "Website origin to analyze, including https:// and hostname, without credentials or a path.",
  "matchType": "Google Ads keyword match type for the forecast.",
  "negativeKeywords": "Keyword phrases excluded from the keyword forecast.",
  "negativeMatchType": "Match type applied to the negative keywords.",
  "geoTargetIds": "Google Ads geo-target constant IDs for the intended locations.",
  "languageId": "Google Ads language constant ID for the keyword request.",
  "languageIds": "Google Ads language constant IDs for the intended audience.",
  "network": "Google Ads search network selector used for planning.",
  "biddingStrategy": "Supported bidding strategy for this temporary forecast. The request does not create a live campaign.",
  "includeAdultKeywords": "Allow adult keyword ideas where supported by the provider and the selected market.",
  "seedKeywords": "Seed keyword phrases from which Google generates keyword ideas.",
  "includeAverageCpc": "Request average cost-per-click metrics when available.",
  "includeDeviceBreakdown": "Include device-specific planning metrics when supported.",
  "includeKeywordConcepts": "Include Google's keyword concept grouping metadata.",
  "startYearMonth": "First year and month of the historical metrics period.",
  "endYearMonth": "Last year and month of the historical metrics period.",
  "includeDismissed": "Include recommendations already dismissed in the account.",
  "operation": "Exact allowlisted operation to execute. Arbitrary provider operations are not accepted.",
  "category": "Category selected from the provider dictionary or field catalogue.",
  "selectable": "Filter the field catalogue by whether the field can appear in SELECT.",
  "filterable": "Filter the field catalogue by whether the field can appear in WHERE.",
  "sortable": "Filter the field catalogue by whether the field can appear in ORDER BY.",
  "pageToken": "Opaque continuation token returned by the preceding provider response.",
  "locationNames": "Human-readable location names for Google to resolve into geo-target constants.",
  "locale": "Locale used for human-readable lookup results.",
  "resource": "Native Google Ads resource from which the GAQL query selects rows.",
  "cursor": "Opaque pagination cursor returned by the preceding response; omit for the first page.",
  "kind": "Entity or request kind whose schema or data is being requested.",
  "startTime": "Beginning of the reporting period as an ISO 8601 timestamp with an explicit timezone.",
  "endTime": "End of the reporting period as an ISO 8601 timestamp with an explicit timezone, after startTime.",
  "reportDimension": "Native dimension used to break down the Snapchat report."
};

export function describeInputSchema<T extends Record<string, any>>(schema:T):T {
  return { ...schema, ...(schema.properties ? {properties:Object.fromEntries(Object.entries(schema.properties).map(([key,value]:[string,any]) => [key,{...value,...(!value.description && PARAMETER_DESCRIPTIONS[key] ? {description:PARAMETER_DESCRIPTIONS[key]} : {})}]))} : {}) };
}
